table 'Dim KPIs'
	lineageTag: b918c3c9-855a-4d1f-8503-8de56e023d9f

	column 'Target Type'
		dataType: string
		lineageTag: 40f1174b-2588-4cdb-b20e-9aeb3caf01af
		summarizeBy: none
		sourceColumn: Target Type

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 70778a51-f7ad-439c-99a2-8da3db00aaba
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e5f16139-8e38-4404-9a06-5e29be23cab3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: double
		lineageTag: cb7625aa-3480-40f2-b495-0dc3eb32ea37
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Year Quarter'
		dataType: string
		lineageTag: 6dd1c833-bfe0-4446-a870-5e8f858ce60b
		summarizeBy: none
		sourceColumn: Year Quarter

		annotation SummarizationSetBy = Automatic

	column 'Shipping Plant'
		dataType: string
		lineageTag: 1f762541-af1b-4d2b-8966-ab68d694297e
		summarizeBy: none
		sourceColumn: Shipping Plant

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: df838f23-eb60-4db8-8420-ba882be2b8a8
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	partition 'Dim KPIs' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://github.com/zakharlukash/projects/raw/main/DimTargets.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Target Type", type text}, {"Year", Int64.Type}, {"Quarter", type text}, {"Target", type number}, {"Year Quarter", type text}, {"Shipping Plant", type text}, {"Unit", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

