table 'Fact Table'
	lineageTag: 05761c16-fffb-4680-8773-ed955b368a5b

	column Index
		dataType: string
		lineageTag: 08f16e10-a337-4d48-a3cd-53cd2b601a2a
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Loading Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3b4ddaff-78f8-4ca3-991e-902585d5ad97
		summarizeBy: none
		sourceColumn: Loading Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Truck Load'
		dataType: string
		lineageTag: f0fa0e7d-bc88-4fd7-84a7-510700ea2369
		summarizeBy: none
		sourceColumn: Truck Load

		annotation SummarizationSetBy = Automatic

	column 'Truck Code'
		dataType: string
		lineageTag: 6fc59d55-6049-46fe-929a-9e3e1d391943
		summarizeBy: none
		sourceColumn: Truck Code

		annotation SummarizationSetBy = Automatic

	column 'Destination Country Code'
		dataType: string
		lineageTag: 5c3b2c66-34eb-42e3-b12e-7f0ea58761d0
		summarizeBy: none
		sourceColumn: Destination Country Code

		annotation SummarizationSetBy = Automatic

	column 'Transportation Mode'
		dataType: string
		lineageTag: 1cf20462-0092-45b8-a3c0-98912b1a67ff
		summarizeBy: none
		sourceColumn: Transportation Mode

		annotation SummarizationSetBy = Automatic

	column KPI
		dataType: string
		lineageTag: 1cbee5bb-30e7-4abc-a2b8-7f723db04551
		summarizeBy: none
		sourceColumn: KPI

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 65b8d775-88d8-444c-937c-cae266675f63
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Actuals Value'
		dataType: int64
		formatString: 0
		lineageTag: a578b718-8dc6-443e-a73e-5a5c36feb9e1
		summarizeBy: sum
		sourceColumn: Actuals Value

		annotation SummarizationSetBy = Automatic

	column 'Target Value'
		dataType: int64
		formatString: 0
		lineageTag: 67d9578d-794b-4f0c-acb7-9795eb6d6116
		summarizeBy: sum
		sourceColumn: Target Value

		annotation SummarizationSetBy = Automatic

	partition 'Fact Table' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://github.com/zakharlukash/projects/raw/main/FactTable.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Index", type text}, {"Loading Date", type date}, {"Truck Load", type text}, {"Equipment Type", type text}, {"Destination Country Code", type text}, {"Transportation Mode", type text}, {"Unit", type text}, {"Shipping Plant", type text}, {"Actuals Value", Int64.Type}, {"Target Value", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Shipping Plant", "City"}, {"Unit", "KPI"}, {"Equipment Type", "Truck Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

